import productImg3 from './assets/randare 3.jpeg';
import productImg4 from './assets/randare 4.jpeg';
import randare1 from './assets/randare 1.jpeg';
import randare2 from './assets/randare 2.jpeg';

export const categoryLabels = {
  'Base & Structure':    'Structuri și Baze Metalice',
  'Culinary Steel':      'Echipamente Inox (Gastronomie)',
  'Bespoke Details':     'Detalii Custom (Feronerie)',
  'Architectural Mesh':  'Plase Arhitecturale',
  'Industrial Art':      'Artă Industrială',
  'Urban Facade':        'Fațade Urbane',
};

export const contactInfo = {
  phone:    '+40 722 123 456',
  email:    'contact@kraft-metalworks.ro',
  address:  'Str. Industriilor 14, Cluj-Napoca, România',
  schedule: 'Luni–Vineri: 09:00–18:00',
};

export const categoryDefaults = {
  'Base & Structure': {
    sizes: [
      { label: 'Standard · H 71 cm', multiplier: 1.0 },
      { label: 'Înalt · H 76 cm', multiplier: 1.1 },
      { label: 'Custom · La Cerere', multiplier: 1.35 },
    ],
    finishes: [
      { label: 'Negru Mat', delta: 0 },
      { label: 'Periat Satinat', delta: 200 },
      { label: 'Inox Natural', delta: 400 },
    ],
  },
  'Culinary Steel': {
    sizes: [
      { label: 'S · 50×50 cm', multiplier: 0.7 },
      { label: 'M · 100×100 cm', multiplier: 1.0 },
      { label: 'L · 100×200 cm', multiplier: 1.8 },
      { label: 'XL · 200×200 cm', multiplier: 3.0 },
    ],
    finishes: [
      { label: 'Carbon Brut', delta: 0 },
      { label: 'Corten Patinat', delta: 300 },
      { label: 'Inox 304', delta: 600 },
      { label: 'Inox 316L Mirror', delta: 1200 },
    ],
  },
  'Bespoke Details': {
    sizes: [
      { label: 'Standard · 1 buc', multiplier: 1.0 },
      { label: 'Set 2 buc', multiplier: 1.8 },
      { label: 'Set 4 buc', multiplier: 3.2 },
    ],
    finishes: [
      { label: 'Negru Mat', delta: 0 },
      { label: 'Satinat Argintiu', delta: 150 },
      { label: 'Bronz Patinat', delta: 300 },
    ],
  },
  'Architectural Mesh': {
    sizes: [
      { label: '1000×2000 mm', multiplier: 1.0 },
      { label: '1200×2400 mm', multiplier: 1.5 },
      { label: 'Custom · La Comandă', multiplier: 2.2 },
    ],
    finishes: [
      { label: 'Negru Mat', delta: 0 },
      { label: 'Zinc Galvanizat', delta: 300 },
      { label: 'Corten Natural', delta: 500 },
    ],
  },
  'Industrial Art': {
    sizes: [
      { label: 'Standard', multiplier: 1.0 },
      { label: 'Mare', multiplier: 1.5 },
      { label: 'Monumental', multiplier: 2.5 },
    ],
    finishes: [
      { label: 'Raw Steel', delta: 0 },
      { label: 'Patinat Aged', delta: 300 },
      { label: 'Vopsit Custom RAL', delta: 500 },
    ],
  },
  'Urban Facade': {
    sizes: [
      { label: '1 ml', multiplier: 1.0 },
      { label: '5 ml', multiplier: 4.5 },
      { label: '10 ml', multiplier: 8.0 },
      { label: 'Custom · Proiect', multiplier: 1.0 },
    ],
    finishes: [
      { label: 'Standard', delta: 0 },
      { label: 'Corten', delta: 500 },
      { label: 'Inox 316L', delta: 1200 },
    ],
  },
};

export const products = [
  // ─── Base & Structure ────────────────────────────────────────────────────────
  {
    id: 'PM-01',
    title: 'Picioare Spider',
    basePrice: 1200,
    price: '1.200 RON',
    badge: 'Best Seller',
    image: productImg3,
    category: 'Base & Structure',
    material: 'Oțel masiv S235 · 8 mm grosime',
    finish: 'Vopsire electrostatică mată',
    detail:
      'Geometrie Spider cu 4 brațe radiante sudate TIG seamless. Ideale pentru blăcuri din lemn masiv sau marmură. Livrare în 10 zile lucrătoare.',
    specs: ['Sarcină max: 350 kg', 'H reglabilă 68–76 cm', 'Suduri șlefuite la invizibil'],
  },
  {
    id: 'PM-02',
    title: 'Picioare X-Industrial',
    basePrice: 1850,
    price: '1.850 RON',
    badge: 'Premium',
    image: productImg4,
    category: 'Base & Structure',
    material: 'Oțel masiv S355 · 10 mm grosime',
    finish: 'Finisaj periat brushed',
    detail:
      'Profil X dublu din platbandă lată de 10 cm. Estetică brutal-industrială cu precizia atelierului elvețian. Suport pentru blăcuri de până la 3 m lungime.',
    specs: ['Sarcină max: 500 kg', 'Finisaj periat 180 grit', 'Șuruburi M10 incluse'],
  },
  {
    id: 'PM-03',
    title: 'Picioare Trapez',
    basePrice: 2400,
    price: '2.400 RON',
    badge: 'Lux',
    image: productImg3,
    category: 'Base & Structure',
    material: 'Oțel masiv S355 · 12 mm grosime',
    finish: 'Vopsire epoxidică negru mat',
    detail:
      'Geometrie trapezoidală asimetrică — un statement vizual puternic. Suduri continue MIG cu cordon uniform, finisate mecanic la oglindă. Dimensionare la cerere.',
    specs: ['Sarcină max: 650 kg', 'Configurabil la comandă', 'Certificare EN 1335'],
  },
  {
    id: 'PM-04',
    title: 'Picioare Hairpin Forjate',
    basePrice: 680,
    price: '680 RON',
    badge: 'Retro',
    image: productImg4,
    category: 'Base & Structure',
    material: 'Oțel bara rotundă Ø12 mm · forjat',
    finish: 'Negru mat satinat',
    detail:
      'Picioare slim hairpin în 3 tije, forjate la cald și sudate TIG. Estetică industrială retro cu rezistență de top. Disponibile în seturi de 4 bucăți.',
    specs: ['Set 4 picioare incluse', 'H: 71 cm standard', 'Vopsire electrostatică'],
  },
  {
    id: 'PM-05',
    title: 'Picioare Trestle Wide',
    basePrice: 1650,
    price: '1.650 RON',
    badge: 'Contract',
    image: productImg3,
    category: 'Base & Structure',
    material: 'Oțel laminat S275 · profil U 60×30 mm',
    finish: 'Vopsire praf negru grofat',
    detail:
      'Design trestle simetric cu traversă centrală și brațe înclinate la 72°. Stabilitate maximă pentru blăcuri mari de conferință sau dining industrial.',
    specs: ['Sarcină max: 400 kg', 'Lățime: 60 cm standard', 'Reglabil ±3 cm'],
  },
  {
    id: 'PM-06',
    title: 'Picioare Cruce Forjată',
    basePrice: 2100,
    price: '2.100 RON',
    badge: 'Artisan',
    image: productImg4,
    category: 'Base & Structure',
    material: 'Oțel masiv S355 · platbandă 80×10 mm',
    finish: 'Patină chimică antică + lac mat',
    detail:
      'Cruce centrală cu 4 brațe la 90°, forjate manual și tratate cu patinare chimică pentru aspect aged premium. Piesă unicat la comandă.',
    specs: ['Unicat la comandă', 'Tratament anti-oxidare', 'Certificat artizanat'],
  },
  {
    id: 'PM-07',
    title: 'Picioare Box Steel U',
    basePrice: 1400,
    price: '1.400 RON',
    badge: 'Minimalist',
    image: productImg3,
    category: 'Base & Structure',
    material: 'Oțel tubular 80×80×4 mm pătrat',
    finish: 'Primer epoxi + lac PU mat',
    detail:
      'Profil pătrat tubular cu decupaj geometric lateral — estetică box minimalist. Ideal pentru birouri executive și săli de conferință arhitecturale.',
    specs: ['Sarcină max: 450 kg', 'Profil 80×80 mm', 'Personalizabil culoare RAL'],
  },
  {
    id: 'PM-08',
    title: 'Picioare H-Frame Dual',
    basePrice: 1950,
    price: '1.950 RON',
    badge: 'Contract Pro',
    image: productImg4,
    category: 'Base & Structure',
    material: 'Oțel masiv S355 · platbandă 100×12 mm',
    finish: 'Vopsire electrostatică antracit',
    detail:
      'Cadru dublu H cu nervuri de rigidizare interioare. Soluția ideală pentru mese de 4–6 metri în spații contract. Livrare cu montaj inclus în Cluj.',
    specs: ['Sarcină max: 600 kg', 'L masă: 2–6 m', 'Montaj inclus Cluj'],
  },
  {
    id: 'PM-09',
    title: 'Picioare Angulare V-Cut',
    basePrice: 1100,
    price: '1.100 RON',
    badge: 'Hotel',
    image: productImg3,
    category: 'Base & Structure',
    material: 'Oțel laminat S275 · platbandă 60×8 mm',
    finish: 'Vopsire praf ivory sau negru',
    detail:
      'Geometrie angulară în formă de V răsturnat — silhouette slim cu stabilitate excelentă. Populare în proiecte hoteliere și restaurante cu design contemporan.',
    specs: ['Sarcină max: 300 kg', 'H: 72 cm', 'Disponibil ivory / negru'],
  },
  {
    id: 'PM-10',
    title: 'Picioare Monobloc Arc',
    basePrice: 3200,
    price: '3.200 RON',
    badge: 'Flagship',
    image: productImg4,
    category: 'Base & Structure',
    material: 'Oțel masiv S355 · tablă 15 mm decupată laser',
    finish: 'Finisaj periat 240 grit sau vopsit',
    detail:
      'Picior unic monobloc tăiat cu laser din tablă groasă de 15 mm și îndoit la presă hidraulică. Zero suduri vizibile — piesă de artă funcțională. Ediție limitată.',
    specs: ['Ediție limitată 50 ex/an', 'Tăiere laser CNC', 'Certificat de origine'],
  },

  // ─── Culinary Steel ──────────────────────────────────────────────────────────
  {
    id: 'GD-01',
    title: 'Grătar Corten Raw',
    basePrice: 3500,
    price: '3.500 RON',
    badge: 'Corten',
    image: productImg4,
    category: 'Culinary Steel',
    material: 'Oțel Corten A · 8 mm tablă groasă',
    finish: 'Patină naturală auto-protectivă',
    detail:
      'Grătar masiv cu bare de 25×8 mm sudate la interval precis de 12 mm. Oțelul Corten dezvoltă în timp un strat rugos estetic care protejează piesa fără vopsire suplimentară.',
    specs: ['Greutate: 38 kg/m²', 'Rezistență termică 800°C', 'Tăiere laser CNC'],
  },
  {
    id: 'GD-02',
    title: 'Grătar Industrial Forged',
    basePrice: 4800,
    price: '4.800 RON',
    badge: 'Heavy Duty',
    image: productImg3,
    category: 'Culinary Steel',
    material: 'Oțel carbon S355J2 · 10 mm',
    finish: 'Vopsire termorezistentă 600°C',
    detail:
      'Structură masivă din bare pătrate de 30×30 mm forjate la cald. Suduri cu penetrare completă, control radiografic. Destinat grătarelor premium și spațiilor publice.',
    specs: ['Greutate: 52 kg/m²', 'Dimensionare custom', 'Garanție 10 ani structurală'],
  },
  {
    id: 'GD-03',
    title: 'Grătar Obsidian Premium',
    basePrice: 6000,
    price: '6.000 RON',
    badge: 'Flagship',
    image: productImg4,
    category: 'Culinary Steel',
    material: 'Oțel inox AISI 316L · 8 mm',
    finish: 'Finisaj oglindă electropolizat',
    detail:
      'Vârful colecției. Bare din inox marin electropolizat cu reflexii neutre și rezistență la coroziune în medii saline. Geometrie hexagonală tăiată cu laser de precizie ±0,05 mm.',
    specs: ['Rezistență salin: 1000h', 'Finisaj Ra < 0.4 μm', 'Certificare alimentară'],
  },
  {
    id: 'GD-04',
    title: 'Grătar Hexagonal Premium',
    basePrice: 5200,
    price: '5.200 RON',
    badge: 'Exclusive',
    image: productImg3,
    category: 'Culinary Steel',
    material: 'Oțel inox AISI 304 · bară rotundă 12 mm',
    finish: 'Finisaj periat 180 grit',
    detail:
      'Structură hexagonală cu celule de 80 mm, suduri TIG tip rosette. Design inspirat din arhitectura industrială japoneză. Comandă minimă 0,5 m².',
    specs: ['Celulă hex 80 mm', 'Suduri rosette TIG', 'Comandă min 0,5m²'],
  },
  {
    id: 'GD-05',
    title: 'Grătar Flat Bar Matrix',
    basePrice: 2800,
    price: '2.800 RON',
    badge: 'Standard Pro',
    image: productImg4,
    category: 'Culinary Steel',
    material: 'Oțel carbon S235 · platbandă 30×6 mm',
    finish: 'Grunduire epoxi bicomponent',
    detail:
      'Matrice de platbenzi verticale sudate la interval de 15 mm, cu bare transversale la 200 mm. Rezistență mecanică superioară față de soluțiile presate standard.',
    specs: ['Interval 15 mm', 'Sarcină: 4 kN/m²', 'Tratament epoxi naval'],
  },
  {
    id: 'GD-06',
    title: 'Grătar Twisted Iron Artisan',
    basePrice: 3900,
    price: '3.900 RON',
    badge: 'Artisan',
    image: productImg3,
    category: 'Culinary Steel',
    material: 'Oțel carbon · bară pătrată 12×12 mm răsucită',
    finish: 'Ceară de lut termorezistentă',
    detail:
      'Bare pătrate răsucite artizanal la cald, fiecare piesă cu torsiune unică. Finisaj cu ceară de protecție termorezistentă. Statement piece cu aspect de forjă medievală.',
    specs: ['Răsucire manuală unică', 'Unicat per comandă', 'Finisaj tradițional ceară'],
  },
  {
    id: 'GD-07',
    title: 'Grătar Arc Perforat CNC',
    basePrice: 4100,
    price: '4.100 RON',
    badge: 'Design CNC',
    image: productImg4,
    category: 'Culinary Steel',
    material: 'Oțel carbon S355 · tablă 8 mm',
    finish: 'Grunduire zinc + vopsire termorezistentă',
    detail:
      'Tablă groasă cu model de perforații arcuite tăiate CNC, alternând goluri eliptice cu bare masive. Joc fascinant de lumini și umbre pentru terase și grătare premium.',
    specs: ['Perforații CNC ±0,05 mm', 'Rezistență 600°C', 'Design exclusiv Kraft'],
  },
  {
    id: 'GD-08',
    title: 'Grătar Diamond Industrial',
    basePrice: 5600,
    price: '5.600 RON',
    badge: 'Structural',
    image: productImg3,
    category: 'Culinary Steel',
    material: 'Oțel carbon S355 · tablă expandată 8 mm',
    finish: 'Zincare la cald + vopsire antracit',
    detail:
      'Tablă expandată industrială romb 50×100 mm, zincare la cald 85 µm garantată 25 de ani. Soluție arhitecturală pentru poduri pietonale și terase suspendate.',
    specs: ['Zincare 85µm / 25 ani', 'Romb 50×100 mm', 'Certificare structurală'],
  },
  {
    id: 'GD-09',
    title: 'Grătar Corten Aged XL',
    basePrice: 4400,
    price: '4.400 RON',
    badge: 'XL Format',
    image: productImg4,
    category: 'Culinary Steel',
    material: 'Oțel Corten B · tablă 10 mm format mare',
    finish: 'Patină accelerată în atelier',
    detail:
      'Format mare de până la 2×4 m dintr-o singură bucată, patinare accelerată controlată în atelier pentru aspect uniform. Soluție pentru fațade și pavimente exterioare.',
    specs: ['Format max 2×4 m', 'Patinare controlată', 'Rezistență 50 ani exterior'],
  },
  {
    id: 'GD-10',
    title: 'Grătar Inox Mirror Architect',
    basePrice: 7200,
    price: '7.200 RON',
    badge: 'Ultra Premium',
    image: productImg3,
    category: 'Culinary Steel',
    material: 'Oțel inox AISI 316L · bară rect 20×10 mm',
    finish: 'Electropolizare oglindă Ra<0,2μm',
    detail:
      'Vârful tehnicii: bare rectangulare din inox marin cu electropolizare de precizie chirurgicală. Folosit în proiecte de arhitectură de nivel mondial. Termen execuție 6 săptămâni.',
    specs: ['Ra < 0,2 μm', 'Inox marin 316L', 'Termen 6 săptămâni'],
  },

  // ─── Bespoke Details ─────────────────────────────────────────────────────────
  {
    id: 'FC-01',
    title: 'Balamale Industriale Heavy',
    basePrice: 890,
    price: '890 RON',
    badge: 'Custom',
    image: productImg3,
    category: 'Bespoke Details',
    material: 'Oțel inox AISI 304 · forjat',
    finish: 'Finisaj satinat mat',
    detail:
      'Set de 2 balamale masive pentru uși grele de până la 180 kg. Ax din oțel inox Ø25 mm cu rulmenți sigilați pe viață. Reglaj tridimensional după montaj.',
    specs: ['Capacitate: 180 kg/ușă', 'Reglaj 3D ±5 mm', 'Rezistență 500.000 cicluri'],
  },
  {
    id: 'FC-02',
    title: 'Mânere Minimalist Custom',
    basePrice: 1250,
    price: '1.250 RON',
    badge: 'Design',
    image: productImg4,
    category: 'Bespoke Details',
    material: 'Oțel masiv Ø30 mm rotund',
    finish: 'Vopsire epoxidică sau periat',
    detail:
      'Mânere extrudate dintr-o singură bară de oțel masiv, fără îmbinări sau suduri vizibile. Prindere cu insert filetat invizibil. Lungime și finisaj la alegere.',
    specs: ['Lungimi: 200–800 mm', 'Prindere invizibilă', 'Configurabil RAL custom'],
  },
  {
    id: 'FC-03',
    title: 'Elemente Fixare Stealth',
    basePrice: 650,
    price: '650 RON',
    badge: 'Arhitectural',
    image: productImg3,
    category: 'Bespoke Details',
    material: 'Oțel inox AISI 316 · CNC',
    finish: 'Anodizat negru sau argintiu',
    detail:
      'Set de console și cleme de fixare cu profil minimalist pentru sisteme de balustrade fără sudură vizibilă. Tăiate CNC cu toleranță de ±0,1 mm pentru ajustaj perfect.',
    specs: ['Toleranță ±0,1 mm', 'Kit complet cu șuruburi', 'Compatibil profil 40×40'],
  },
  {
    id: 'FC-04',
    title: 'Zăvoare Masive Barn Slide',
    basePrice: 450,
    price: '450 RON',
    badge: 'Barn Door',
    image: productImg4,
    category: 'Bespoke Details',
    material: 'Oțel masiv S235 · bară rotundă 25 mm',
    finish: 'Vopsire manuală negru mat',
    detail:
      'Set complet barn door din oțel masiv pentru uși glisante industriale. Include bară Ø25 mm, ghidaje și cârlige de perete. Estetic industrial autentic.',
    specs: ['Compatibil uși 50–120 cm', 'Bară inclusă 1,2 m', 'Montaj plug-and-play'],
  },
  {
    id: 'FC-05',
    title: 'Console Perete Minimalist',
    basePrice: 720,
    price: '720 RON',
    badge: 'Loft',
    image: productImg3,
    category: 'Bespoke Details',
    material: 'Oțel laminat S235 · platbandă 50×8 mm',
    finish: 'Vopsire epoxidică neagră',
    detail:
      'Console de raft cu profil L slim, tăiate cu plasmă și sudate TIG. Prindere în perete cu 4 puncte M8 și capete rotunjite CNC. Sarcină admisă 120 kg/pereche.',
    specs: ['Sarcină: 120 kg/pereche', 'Lungimi 30–80 cm', 'Personalizabil lățime'],
  },
  {
    id: 'FC-06',
    title: 'Prinderi Sticlă Point Fix',
    basePrice: 980,
    price: '980 RON',
    badge: 'Structural Glass',
    image: productImg4,
    category: 'Bespoke Details',
    material: 'Oțel inox AISI 316 · frezat CNC',
    finish: 'Satinat mat sau cromat oglindă',
    detail:
      'Sistem de prindere punctuală pentru sticlă structurală 12–21 mm. Rotulă internă ±15° pentru compensarea toleranțelor de montaj. Zero șuruburi vizibile.',
    specs: ['Compatibil sticlă 12–21 mm', 'Rotulă ±15°', 'Certificare structurală'],
  },
  {
    id: 'FC-07',
    title: 'Suporți Raft Industrial',
    basePrice: 380,
    price: '380 RON',
    badge: 'Loft Style',
    image: productImg3,
    category: 'Bespoke Details',
    material: 'Oțel laminat S235 · profil T 40×40 mm',
    finish: 'Finisaj negru mat sau natural',
    detail:
      'Set de 2 suporți pentru rafturi în stil loft industrial. Prindere pe șină de perete sau direct în beton. Design cu nervuri vizibile. Capacitate 80 kg per suport.',
    specs: ['Set 2 suporți', 'Sarcină: 80 kg/suport', 'H raft: 25–60 cm reglabil'],
  },
  {
    id: 'FC-08',
    title: 'Cuplaje Structurale Heavy',
    basePrice: 1100,
    price: '1.100 RON',
    badge: 'Heavy Duty',
    image: productImg4,
    category: 'Bespoke Details',
    material: 'Oțel masiv S355 · frezat CNC 3 axe',
    finish: 'Zincare electrolitică + vopsire',
    detail:
      'Cuplaje pentru structuri tubulare din oțel folosite în pergole, carporturi și structuri temporare. Toleranță ±0,05 mm pentru asamblare fără forțare.',
    specs: ['Toleranță ±0,05 mm', 'Compatibil tub Ø48', 'Set 4 cuplaje'],
  },
  {
    id: 'FC-09',
    title: 'Mânere Bară Continuă',
    basePrice: 1650,
    price: '1.650 RON',
    badge: 'Through-Bolt',
    image: productImg3,
    category: 'Bespoke Details',
    material: 'Oțel masiv Ø32 mm cu manșoane inox',
    finish: 'Periat sau vopsire RAL custom',
    detail:
      'Mânere continue pentru uși pivotante grele, cu sistem de prindere through-bolt ascunsă. Lungime personalizabilă până la 2,4 m. Compatibil balamale pivot Kraft.',
    specs: ['Lungimi până la 2,4 m', 'Prindere through-bolt', 'Compatibil uși 300 kg'],
  },
  {
    id: 'FC-10',
    title: 'Kit Fixare Balustradă',
    basePrice: 1900,
    price: '1.900 RON',
    badge: 'Kit Complet',
    image: productImg4,
    category: 'Bespoke Details',
    material: 'Oțel inox AISI 316 · ancore chimice incluse',
    finish: 'Satinat mat',
    detail:
      'Kit complet de montaj pentru balustrade fără sudură pe șantier: plăci de bază, ancore chimice HILTI, șuruburi inox A4 și profile de ajustare. Montaj 1 zi pentru 20 ml.',
    specs: ['Kit 20 ml balustradă', 'Ancore HILTI incluse', 'Instalare 1 zi'],
  },

  // ─── Architectural Mesh ──────────────────────────────────────────────────────
  {
    id: 'AM-01',
    title: 'Panou Mesh Industrial',
    basePrice: 1800,
    price: '1.800 RON',
    badge: 'Bestseller',
    image: productImg3,
    category: 'Architectural Mesh',
    material: 'Oțel carbon S235 · sârmă 4 mm sudată',
    finish: 'Vopsire electrostatică negru mat',
    detail: 'Panou mesh sudat cu ochiuri de 50×50 mm, cadru din platbandă 40×4 mm. Ideal ca separator de spațiu, panou de placare sau element de grădină verticală.',
    specs: ['Dimensiuni: 1000×2000 mm', 'Personalizabil la comandă', 'Montaj rapid cu bride'],
  },
  {
    id: 'AM-02',
    title: 'Separator Hexagonal Loft',
    basePrice: 2600,
    price: '2.600 RON',
    badge: 'Design',
    image: productImg4,
    category: 'Architectural Mesh',
    material: 'Oțel carbon · tablă expandată 3 mm',
    finish: 'Patinare chimică sau vopsire',
    detail: 'Panou separator cu model hexagonal tăiat laser, montat în cadru metalic aparent. Joc dinamic de lumini și umbre. Disponibil în formate standard sau la comandă.',
    specs: ['Format max: 1200×2400 mm', 'Deschidere hex: 40 mm', 'Greutate: 8 kg/m²'],
  },
  {
    id: 'AM-03',
    title: 'Sistem Placare Fațadă',
    basePrice: 3400,
    price: '3.400 RON/m²',
    badge: 'Arhitectural',
    image: productImg3,
    category: 'Architectural Mesh',
    material: 'Oțel Corten A · tablă 3 mm perforată',
    finish: 'Patină naturală Corten',
    detail: 'Sistem modular de placare exterioară cu tablă Corten perforată, fixată pe structură secundară din profile galvanizate. Reduce sarcina termică și creează identitate vizuală.',
    specs: ['Module 600×1200 mm', 'Structură galvanizată inclusă', 'Garanție 30 ani exterior'],
  },

  // ─── Industrial Art ──────────────────────────────────────────────────────────
  {
    id: 'IA-01',
    title: 'Sculptură Perete Raw Steel',
    basePrice: 4500,
    price: '4.500 RON',
    badge: 'Unicat',
    image: productImg4,
    category: 'Industrial Art',
    material: 'Oțel carbon S355 · tablă 6 mm decupată laser',
    finish: 'Ulei de protecție + lac mat',
    detail: 'Compoziție abstractă tăiată laser din tablă groasă, cu relief creat prin îndoiri la presă. Fiecare piesă este unică. Livrată gata de montaj cu sistem de prindere invizibil.',
    specs: ['Dimensiune: 800×600 mm', 'Sistem prindere inclus', 'Certificat de autenticitate'],
  },
  {
    id: 'IA-02',
    title: 'Consolă Artizanală Flotantă',
    basePrice: 2200,
    price: '2.200 RON',
    badge: 'Artisan',
    image: productImg3,
    category: 'Industrial Art',
    material: 'Oțel masiv S355 · platbandă 80×12 mm',
    finish: 'Patinare chimică aged + lac mat',
    detail: 'Consolă de perete cu geometrie angulară asimetrică, forjată și patinată manual. Combinată cu blat de lemn sau sticlă, devine un statement funcțional-sculptural.',
    specs: ['Lungime 60 cm', 'Sarcină: 80 kg', 'Finisaj unic per comandă'],
  },
  {
    id: 'IA-03',
    title: 'Lampă Industrială Forge',
    basePrice: 1650,
    price: '1.650 RON',
    badge: 'Limited',
    image: productImg4,
    category: 'Industrial Art',
    material: 'Oțel carbon · bară Ø20 mm turnată',
    finish: 'Negru mat oxidat + ceară',
    detail: 'Lampă de podea cu braț articulat din oțel forjat manual. Soclu greu anti-răsturnare, cablaj textile inclus. Ediție limitată 30 bucăți/an.',
    specs: ['H: 160 cm (podea)', 'Soclu: 4 kg', 'Ediție limitată 30 ex/an'],
  },

  // ─── Urban Facade ────────────────────────────────────────────────────────────
  {
    id: 'UF-01',
    title: 'Sistem Balustradă Modular',
    basePrice: 2800,
    price: '2.800 RON/ml',
    badge: 'System',
    image: productImg3,
    category: 'Urban Facade',
    material: 'Oțel inox AISI 316L + sticlă securizată',
    finish: 'Inox satinat + sticlă low-iron',
    detail: 'Sistem modular de balustradă cu montanți din inox și panou de sticlă 12 mm fixată cu cleme stealth. Instalare rapidă, aspect premium. Compatibil interior/exterior.',
    specs: ['Înălțime: 100 cm standard', 'Sticlă low-iron inclusă', 'Montaj 1 zi/20 ml'],
  },
  {
    id: 'UF-02',
    title: 'Poartă Pivot Cantilever',
    basePrice: 8500,
    price: '8.500 RON',
    badge: 'Premium',
    image: productImg4,
    category: 'Urban Facade',
    material: 'Oțel masiv S355 · tablă 10 mm',
    finish: 'Vopsire electrostatică sau Corten',
    detail: 'Poartă pivotantă cantilever fără șine la sol, cu mecanism pivot ascuns și acționare electrică opțională. Design minimalist, rezistentă la solicitări intensive.',
    specs: ['Lățime max: 4 m', 'Mecanism pivot inclus', 'Motor electric opțional'],
  },
  {
    id: 'UF-03',
    title: 'Parapet Metalic Exterior',
    basePrice: 1200,
    price: '1.200 RON/ml',
    badge: 'Structural',
    image: productImg3,
    category: 'Urban Facade',
    material: 'Oțel zincat S235 + vopsire pulbere',
    finish: 'Zincare 85µm + RAL custom',
    detail: 'Parapet structural pentru balcoane și terase, cu umplutură din tablă expandată sau lamele orizontale. Conform normelor EN 1337. Proiectat pentru longevitate maximă.',
    specs: ['Înălțime: 100–120 cm', 'Zincare 85µm garantat', 'Certificare EN 1337'],
  },
];

export const customProjects = [
  {
    id: 'CP-01',
    title: 'Poartă de Intrare Monumentală',
    location: 'Cluj-Napoca',
    year: '2024',
    type: 'Poartă Pivotantă',
    description: 'Poartă pivotantă din oțel masiv 12 mm, finisaj Corten cu patină controlată. Înălțime 3,2 m, acționare electrică integrată invizibil în cadrul structural.',
    image: productImg3,
  },
  {
    id: 'CP-02',
    title: 'Balustradă Elicoidală Loft',
    location: 'București',
    year: '2024',
    type: 'Balustradă Arhitecturală',
    description: 'Balustradă cu panou de sticlă securizată 12 mm și mână curentă din inox AISI 316L electropolizat. Curbură elicoidală calculată CNC pentru o scară de 4 niveluri.',
    image: productImg4,
  },
  {
    id: 'CP-03',
    title: 'Pergolă Industrială Premium',
    location: 'Timișoara',
    year: '2023',
    type: 'Structură Exterioară',
    description: 'Pergolă din profile HEA 160, vopsire termorezistentă antracit, cu rigle pentru plante cățărătoare. Suprafață 48 m², montaj finalizat în 3 zile lucrătoare.',
    image: randare1,
  },
  {
    id: 'CP-04',
    title: 'Scări Suspendate Floating',
    location: 'Cluj-Napoca',
    year: '2023',
    type: 'Scări Arhitecturale',
    description: 'Structură centrală din oțel tăiată CNC cu trepte din lemn masiv stejar 60 mm. Efect floating prin prinderi ascunse și iluminat LED integrat în structură.',
    image: randare2,
  },
  {
    id: 'CP-05',
    title: 'Compartimentare Loft Raw Steel',
    location: 'Brașov',
    year: '2023',
    type: 'Design Interior',
    description: 'Sistem de compartimentare din profile din oțel negru cu panouri de sticlă clară. Suprafață totală 22 m². Stil factory vintage autentic, realizat în 5 zile.',
    image: productImg3,
  },
  {
    id: 'CP-06',
    title: 'Balcon Corten Arhitectural',
    location: 'Sibiu',
    year: '2022',
    type: 'Structură Balcon',
    description: 'Balcon cantilever din grindă IPE 200 ancorată în structura de beton, cu balustradă Corten perforată laser. Design premiat la concursul național de arhitectură.',
    image: productImg4,
  },
];
